name: "Pull Request Labeler"

# PRが作成、更新、再オープンされた時に実行
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

# 必要な権限を設定
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    name: "Auto Label PR"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Apply Labels"
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
